spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/bankingsystem
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

app:
  initalDelayInMillis: 3000
  fixedRateInMillis: 15000
server:
  error:
    include-message: always
    include-exception: true
