spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/bankingsystem
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
  mail:
    host: smtp.gmail.com
    port: 587
    username: arrkadique@gmail.com
    password: nlzs rbpb zagd arfr
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

app:
  initalDelayInMillis: 3000
  fixedRateInMillis: 15000
server:
  error:
    include-message: always
    include-exception: true
  port: 9000
logging:
  level:
    org.springframework.web.servlet.handler.HandlerMappingIntrospector: error

